import React, { useState } from "react";
import { cn } from "@/lib/utils";
import { Server, Cloud, ExternalLink, Monitor, Wifi, HardDrive, Code2, Play, Copy, Check, Download } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const cloudProviders = [
  { name: "Lambda Cloud", url: "https://lambdalabs.com/service/gpu-cloud", gpu: "A100 / H100", price: "From $1.10/hr", description: "Best GPU cloud for ML training", color: "from-purple-500 to-indigo-500" },
  { name: "RunPod", url: "https://www.runpod.io/", gpu: "A100 / RTX 4090", price: "From $0.44/hr", description: "Affordable GPU rentals with flexible billing", color: "from-blue-500 to-cyan-500" },
  { name: "Vast.ai", url: "https://vast.ai/", gpu: "Various", price: "From $0.20/hr", description: "GPU marketplace with cheapest options", color: "from-emerald-500 to-green-500" },
  { name: "AWS (EC2 P4d)", url: "https://aws.amazon.com/ec2/instance-types/p4/", gpu: "A100 × 8", price: "From $32.77/hr", description: "Enterprise-grade with full AWS ecosystem", color: "from-orange-500 to-amber-500" },
  { name: "Google Cloud (A3)", url: "https://cloud.google.com/compute/docs/gpus", gpu: "H100 × 8", price: "On demand", description: "Integrated with TPUs and Vertex AI", color: "from-red-500 to-rose-500" },
  { name: "Paperspace", url: "https://www.paperspace.com/", gpu: "A100 / RTX", price: "From $2.30/hr", description: "Simple ML infrastructure with Gradient", color: "from-teal-500 to-cyan-500" },
];

// Notebook options with their local URI schemes (if available)
const notebookOptions = [
  {
    key: "colab",
    name: "Google Colab",
    description: "Free GPU/TPU in browser — easy to share",
    url: "https://colab.research.google.com/",
    badge: "Free tier",
    color: "from-orange-500 to-yellow-400",
    localScheme: null, // web only
  },
  {
    key: "kaggle",
    name: "Kaggle Notebooks",
    description: "30 GPU hours/week free, fast setup",
    url: "https://www.kaggle.com/code",
    badge: "Free",
    color: "from-cyan-500 to-blue-400",
    localScheme: null, // web only
  },
  {
    key: "vscode",
    name: "VS Code",
    description: "Open a local Jupyter notebook in VS Code",
    url: "https://code.visualstudio.com/",
    badge: "Local",
    color: "from-blue-600 to-indigo-500",
    localScheme: "vscode://", // try to open VS Code
  },
  {
    key: "jupyterlab",
    name: "JupyterLab",
    description: "Self-hosted Jupyter Lab on localhost:8888",
    url: "http://localhost:8888/lab",
    badge: "Local",
    color: "from-emerald-500 to-teal-400",
    localScheme: "http://localhost:8888/lab",
  },
  {
    key: "sagemaker",
    name: "AWS SageMaker",
    description: "Managed Jupyter on AWS with autoscaling",
    url: "https://aws.amazon.com/sagemaker/",
    badge: "Paid",
    color: "from-amber-500 to-orange-400",
    localScheme: null,
  },
  {
    key: "vertex_ai",
    name: "Vertex AI Workbench",
    description: "Google-managed notebooks with GPU",
    url: "https://cloud.google.com/vertex-ai/docs/workbench",
    badge: "Paid",
    color: "from-red-500 to-rose-400",
    localScheme: null,
  },
];

function generateTrainScript(config) {
  const model = config.model || "resnet50";
  const dataset = config.dataset || "cifar10";
  const epochs = config.epochs || 100;
  const batchSize = config.batch_size || 32;
  const lr = config.learning_rate || 0.001;
  const checkpoint = config.checkpoint_path || "./checkpoints";

  return `#!/usr/bin/env python3
"""
Auto-generated training script
Model: ${model}  |  Dataset: ${dataset}
Generated by Vision Lab
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as transforms
import os

# ─── Config ───────────────────────────────────────────────────────────────────
MODEL_NAME   = "${model}"
DATASET_NAME = "${dataset}"
EPOCHS       = ${epochs}
BATCH_SIZE   = ${batchSize}
LEARNING_RATE = ${lr}
CHECKPOINT_DIR = "${checkpoint}"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ─── Dataset ──────────────────────────────────────────────────────────────────
transform = transforms.Compose([
    transforms.Resize(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225]),
])

${dataset === "cifar10" ? `train_dataset = torchvision.datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
val_dataset   = torchvision.datasets.CIFAR10(root="./data", train=False, download=True, transform=transform)
NUM_CLASSES = 10` :
dataset === "cifar100" ? `train_dataset = torchvision.datasets.CIFAR100(root="./data", train=True, download=True, transform=transform)
val_dataset   = torchvision.datasets.CIFAR100(root="./data", train=False, download=True, transform=transform)
NUM_CLASSES = 100` :
dataset === "mnist" ? `transform = transforms.Compose([transforms.Resize(224), transforms.Grayscale(3), transforms.ToTensor()])
train_dataset = torchvision.datasets.MNIST(root="./data", train=True, download=True, transform=transform)
val_dataset   = torchvision.datasets.MNIST(root="./data", train=False, download=True, transform=transform)
NUM_CLASSES = 10` :
`# TODO: Replace with your dataset loader
# train_dataset = torchvision.datasets.ImageFolder("path/to/train", transform=transform)
# val_dataset   = torchvision.datasets.ImageFolder("path/to/val", transform=transform)
NUM_CLASSES = 1000  # Update to your number of classes
raise NotImplementedError("Set up your dataset above and remove this line")`}

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=4, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True)

# ─── Model ────────────────────────────────────────────────────────────────────
${model.startsWith("resnet") ? `model = torchvision.models.${model.replace("-", "_")}(weights="DEFAULT")
model.fc = nn.Linear(model.fc.in_features, NUM_CLASSES)` :
model.startsWith("vgg") ? `model = torchvision.models.${model.replace("-", "_")}(weights="DEFAULT")
model.classifier[6] = nn.Linear(4096, NUM_CLASSES)` :
model.startsWith("efficientnet") ? `model = torchvision.models.${model.replace("-", "_")}(weights="DEFAULT")
model.classifier[1] = nn.Linear(model.classifier[1].in_features, NUM_CLASSES)` :
model === "mobilenet_v3" ? `model = torchvision.models.mobilenet_v3_large(weights="DEFAULT")
model.classifier[3] = nn.Linear(model.classifier[3].in_features, NUM_CLASSES)` :
`model = torchvision.models.resnet50(weights="DEFAULT")
model.fc = nn.Linear(model.fc.in_features, NUM_CLASSES)
# Note: ${model} — adjust the head replacement above accordingly`}
model = model.to(DEVICE)

# ─── Optimizer & Loss ─────────────────────────────────────────────────────────
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

# ─── Training Loop ────────────────────────────────────────────────────────────
best_val_acc = 0.0

for epoch in range(1, EPOCHS + 1):
    # Train
    model.train()
    train_loss, correct, total = 0.0, 0, 0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * inputs.size(0)
        _, predicted = outputs.max(1)
        correct += predicted.eq(labels).sum().item()
        total += labels.size(0)

    train_acc  = 100.0 * correct / total
    train_loss = train_loss / total

    # Validate
    model.eval()
    val_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item() * inputs.size(0)
            _, predicted = outputs.max(1)
            correct += predicted.eq(labels).sum().item()
            total += labels.size(0)

    val_acc  = 100.0 * correct / total
    val_loss = val_loss / total
    scheduler.step()

    print(f"Epoch [{epoch:3d}/{EPOCHS}]  "
          f"Train Loss: {train_loss:.4f}  Train Acc: {train_acc:.2f}%  "
          f"Val Loss: {val_loss:.4f}  Val Acc: {val_acc:.2f}%")

    # Save best checkpoint
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), os.path.join(CHECKPOINT_DIR, "best.pth"))
        print(f"  → Saved best model (val_acc={val_acc:.2f}%)")

print(f"\\nTraining complete. Best Val Acc: {best_val_acc:.2f}%")
`;
}

function generateRequirements() {
  return `torch>=2.0.0
torchvision>=0.15.0
tqdm
pillow
`;
}

function CodeBlock({ code, filename }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([code], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
  };

  return (
    <div className="rounded-xl border border-white/10 bg-[#0a0a12] overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 border-b border-white/5 bg-white/[0.02]">
        <span className="text-[11px] font-mono text-slate-400">{filename}</span>
        <div className="flex gap-2">
          <button onClick={handleCopy} className="flex items-center gap-1 text-[10px] text-slate-500 hover:text-white transition-colors">
            {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
            {copied ? "Copied!" : "Copy"}
          </button>
          <button onClick={handleDownload} className="flex items-center gap-1 text-[10px] text-slate-500 hover:text-white transition-colors">
            <Download className="w-3 h-3" />
            Download
          </button>
        </div>
      </div>
      <pre className="p-4 text-[11px] font-mono text-slate-300 overflow-x-auto max-h-80 overflow-y-auto leading-relaxed whitespace-pre">
        {code}
      </pre>
    </div>
  );
}

function NotebookCard({ nb }) {
  const isLocal = nb.localScheme !== null;

  const handleOpen = (e) => {
    e.preventDefault();
    if (nb.localScheme && (nb.localScheme.startsWith("http://localhost") || nb.localScheme.startsWith("vscode://"))) {
      window.open(nb.localScheme, "_blank");
    } else {
      window.open(nb.url, "_blank");
    }
  };

  return (
    <div
      className="group rounded-2xl border border-white/10 bg-white/[0.02] p-5 transition-all hover:border-white/20 hover:bg-white/[0.04] hover:scale-[1.02] cursor-pointer"
      onClick={handleOpen}
    >
      <div className="flex items-start justify-between mb-3">
        <div className={cn("w-8 h-8 rounded-lg bg-gradient-to-br flex items-center justify-center", nb.color)}>
          <BookOpen className="w-4 h-4 text-white" />
        </div>
        <div className="flex items-center gap-1.5">
          <span className={cn(
            "text-[10px] font-semibold px-2 py-0.5 rounded-full",
            isLocal ? "text-emerald-400 bg-emerald-500/10" : "text-slate-400 bg-white/5"
          )}>
            {nb.badge}
          </span>
          <ExternalLink className="w-3 h-3 text-slate-600 group-hover:text-slate-400 transition-colors" />
        </div>
      </div>
      <h4 className="font-semibold text-white text-sm">{nb.name}</h4>
      <p className="text-xs text-slate-400 mt-1">{nb.description}</p>
      {isLocal && (
        <p className="text-[10px] text-emerald-400 mt-2 flex items-center gap-1">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
          Click to try opening locally
        </p>
      )}
    </div>
  );
}

export default function ServerConfig({ config, onChange }) {
  const serverType = config.server_type || "";
  const [activeCodeTab, setActiveCodeTab] = useState("train");

  const trainScript = generateTrainScript(config);
  const requirements = generateRequirements();

  return (
    <div className="space-y-6">
      {/* Server Type Selection */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { key: "browser", Icon: Play, gradient: "from-emerald-500 to-teal-400", title: "Run in Browser", sub: "Simulate training right here, no setup needed" },
          { key: "own_server", Icon: Server, gradient: "from-slate-500 to-slate-400", title: "I have a server", sub: "Configure your own GPU server" },
          { key: "cloud_recommendation", Icon: Cloud, gradient: "from-blue-500 to-cyan-400", title: "Rent a cloud GPU", sub: "Get cloud provider recommendations" },
          { key: "get_code", Icon: Code2, gradient: "from-violet-500 to-fuchsia-400", title: "Get the code", sub: "Export ready-to-run training scripts" },
        ].map(({ key, Icon, gradient, title, sub }) => (
          <button
            key={key}
            onClick={() => onChange({ server_type: key })}
            className={cn(
              "relative text-left rounded-2xl border p-5 transition-all duration-300 hover:scale-[1.01]",
              serverType === key
                ? "border-white/30 bg-white/[0.06] shadow-lg"
                : "border-white/10 bg-white/[0.02] hover:border-white/20"
            )}
          >
            <div className={cn("w-11 h-11 rounded-xl bg-gradient-to-br flex items-center justify-center mb-4", gradient)}>
              <Icon className="w-5 h-5 text-white" />
            </div>
            <h3 className="font-semibold text-white text-sm">{title}</h3>
            <p className="text-xs text-slate-400 mt-1">{sub}</p>
          </button>
        ))}
      </div>

      {/* Browser training info */}
      {serverType === "browser" && (
        <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6 space-y-3">
          <h3 className="text-sm font-semibold text-white flex items-center gap-2">
            <Play className="w-4 h-4 text-emerald-400" />
            In-Browser Training
          </h3>
          <p className="text-xs text-slate-400 leading-relaxed">
            Training will run as a live simulation directly in your browser — no server, no GPU, no setup required. You'll see real-time accuracy and loss curves epoch by epoch. Perfect for validating your configuration before committing to a real training run.
          </p>
          <div className="flex flex-wrap gap-2 mt-1">
            {["No GPU needed", "Live graphs", "Instant start", "Saves to dashboard"].map(tag => (
              <span key={tag} className="text-[10px] font-semibold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded-full">{tag}</span>
            ))}
          </div>
        </div>
      )}

      {/* Own Server */}
      {serverType === "own_server" && (
        <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 space-y-5">
          <h3 className="text-sm font-semibold text-white flex items-center gap-2">
            <Monitor className="w-4 h-4 text-emerald-400" />
            Server Details
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-xs text-slate-400">Host / IP Address</Label>
              <Input placeholder="e.g. 192.168.1.100" value={config.server_host || ""} onChange={(e) => onChange({ server_host: e.target.value })} className="bg-white/5 border-white/10 text-white placeholder:text-slate-600" />
            </div>
            <div className="space-y-2">
              <Label className="text-xs text-slate-400">SSH Port</Label>
              <Input placeholder="22" value={config.server_port || ""} onChange={(e) => onChange({ server_port: e.target.value })} className="bg-white/5 border-white/10 text-white placeholder:text-slate-600" />
            </div>
            <div className="space-y-2">
              <Label className="text-xs text-slate-400">GPU Type</Label>
              <Select value={config.server_gpu || ""} onValueChange={(v) => onChange({ server_gpu: v })}>
                <SelectTrigger className="bg-white/5 border-white/10 text-white"><SelectValue placeholder="Select GPU" /></SelectTrigger>
                <SelectContent>
                  {["rtx_3090", "rtx_4090", "a100_40gb", "a100_80gb", "h100", "v100", "other"].map(v => (
                    <SelectItem key={v} value={v}>{v.replace(/_/g, " ").toUpperCase()}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs text-slate-400">Checkpoint Save Path</Label>
              <Input placeholder="/home/user/checkpoints/" value={config.checkpoint_path || ""} onChange={(e) => onChange({ checkpoint_path: e.target.value })} className="bg-white/5 border-white/10 text-white placeholder:text-slate-600" />
            </div>
          </div>
        </div>
      )}

      {/* Cloud Recommendations */}
      {serverType === "cloud_recommendation" && (
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-white flex items-center gap-2"><Wifi className="w-4 h-4 text-blue-400" />Recommended GPU Cloud Providers</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {cloudProviders.map((p) => (
              <a key={p.name} href={p.url} target="_blank" rel="noopener noreferrer"
                className="group rounded-2xl border border-white/10 bg-white/[0.02] p-5 transition-all hover:border-white/20 hover:bg-white/[0.04] hover:scale-[1.02]">
                <div className="flex items-start justify-between mb-3">
                  <div className={cn("w-8 h-8 rounded-lg bg-gradient-to-br flex items-center justify-center", p.color)}>
                    <HardDrive className="w-4 h-4 text-white" />
                  </div>
                  <ExternalLink className="w-3.5 h-3.5 text-slate-600 group-hover:text-slate-400 transition-colors" />
                </div>
                <h4 className="font-semibold text-white text-sm">{p.name}</h4>
                <p className="text-xs text-slate-400 mt-1">{p.description}</p>
                <div className="flex items-center gap-2 mt-3">
                  <span className="text-[10px] font-mono text-slate-500 bg-white/5 px-2 py-0.5 rounded-full">{p.gpu}</span>
                  <span className="text-[10px] font-semibold text-emerald-400">{p.price}</span>
                </div>
              </a>
            ))}
          </div>
        </div>
      )}

      {/* Get the Code */}
      {serverType === "get_code" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <Code2 className="w-4 h-4 text-violet-400" />
              Generated Training Code
            </h3>
            <p className="text-[10px] text-slate-500">Based on your current dataset & model selection</p>
          </div>

          {/* Tab selector */}
          <div className="flex gap-2">
            {[
              { id: "train", label: "train.py" },
              { id: "requirements", label: "requirements.txt" },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveCodeTab(tab.id)}
                className={cn(
                  "text-[11px] font-mono px-3 py-1.5 rounded-lg border transition-all",
                  activeCodeTab === tab.id
                    ? "border-violet-500/50 bg-violet-500/10 text-violet-300"
                    : "border-white/10 bg-white/[0.02] text-slate-500 hover:text-slate-300"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {activeCodeTab === "train" && (
            <CodeBlock code={trainScript} filename="train.py" />
          )}
          {activeCodeTab === "requirements" && (
            <CodeBlock code={requirements} filename="requirements.txt" />
          )}

          <div className="rounded-xl border border-violet-500/20 bg-violet-500/5 p-4 text-xs text-violet-300">
            Run with: <span className="font-mono">pip install -r requirements.txt &amp;&amp; python train.py</span>
          </div>
        </div>
      )}

    </div>
  );
}
